# Generated by Django 5.0.4 on 2024-05-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(max_length=50),
        ),
    ]
