# Generated by Django 5.0.4 on 2024-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_remove_file_file_file_created_at_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
