# Generated by Django 5.0.4 on 2024-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="profile_avatars/default_avatar.png",
                upload_to="profile_avatars/",
            ),
        ),
    ]
